- name: "Install dependancy"
  apt:
    name: nginx
    state: latest

- name: "Enable nginx"
  service:
    name: nginx
    enabled: yes

- name: "Start nginx"
  service: 
    name: nginx
    state: latest
